name: gestorReferenciaPagamentoUi
description: Sistema Sibys da Direção dos Impostos de São Tomé e Principe.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  web_socket_channel: ^1.1.0
  font_awesome_flutter: ^8.8.1
  flutter_secure_storage: ^3.3.3
  http: ^0.12.1
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1+1
  flutter_modular: ^1.3.0
  dio: ^3.0.9
  intl: ^0.16.1
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

vars:
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner

scripts:
    build: $clean & $get & $runner build --delete-conflicting-outputs
    watch: $clean & $get & $runner watch --delete-conflicting-outputs
    w: $runner watch
